package com.parvez.pojo;
// Generated Feb 1, 2018 7:25:12 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="test"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Student  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String studentName;

    public Student() {
    }

	
    public Student(String studentName) {
        this.studentName = studentName;
    }
    public Student(String email, String studentName) {
       this.email = email;
       this.studentName = studentName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="email", unique=true)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="student_name", nullable=false)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }




}


