package com.coderbd.pojo;
// Generated Mar 4, 2018 9:31:13 AM by Hibernate Tools 4.3.1

import com.coderbd.dao.UserDao;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student",
         catalog = "user"
)
public class Student implements java.io.Serializable {

    private Integer id;
    private String name;
    private String password;

    public Student() {
    }

    public Student(String name, String password) {
        this.name = name;
        this.password = password;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", length = 25)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "password", length = 25)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String execute() {
        UserDao.saveStudent(this);
        return "success";
    }

    public String login() {
        int i = UserDao.validStudent(this);
        if (i > 0) {
            return "success";
        } else  {
            return "error";
        }
    }

}
